Logging:
  LogLevel:
    Default: Information
    Microsoft.AspNetCore: Warning
AllowedHosts: "*"

Serilog:
  MinimumLevel: 
    Default: "Information"
    Override:
      Microsoft: "Warning"
      Microsoft.Hosting.Lifetime: "Information"
      Microsoft.AspNetCore: "Warning"
  Using:  
    - Serilog.Enrichers.ClientInfo
    - Serilog.Expressions
    - Serilog.Exceptions
    - Serilog.Exceptions.Refit
  Enrich:
    - Name: WithCorrelationId
      Args: 
        addValueIfHeaderAbsence: false
    - Name: WithExceptionDetails
      Args:
        DefaultDestructuringEnabled: true
      Destructurers:
        - Name: "Serilog.Exceptions.Refit.Destructurers.ApiExceptionDestructurer, Serilog.Exceptions.Refit"
  Filter:
    - Name: "ByExcluding"
      Args:
        expression: "@mt = 'An unhandled exception has occurred while executing the request.'"
  WriteTo: 
    - Name: Console
      Args:
        formatter:
          type: "Serilog.Templates.ExpressionTemplate, Serilog.Expressions"
          template: "[{@t:yyyy-MM-ddTHH:mm:ss} {Coalesce(CorrelationId, '0000000000000:00000000')} {@l:u3}] {@m}\n{@x}"

Yarp:
  Routes:
    route1:
      ClusterId: gitlab
      Match:
        Path: "{**catch-all}"
      Transforms:
        - RequestHeadersCopy: 'true'
  Clusters:
    gitlab:
      Destinations:
        destination1:
          Address: https://gitlab.apps.yunqi.studio

AppConfig:
  GitlabBaseUrl: https://gitlab.apps.yunqi.studio
