Yarp:
  Clusters:
    gitlab:
      HttpClient:
        DangerousAcceptAnyServerCertificate: true    
      Destinations:
        destination1:
          Address: https://gitlab

AppConfig:
  GitlabBaseUrl: https://gitlab
